export const EMPLOYEES_LOADED     = 'EMPLOYEES_LOADED';
export const EMPLOYEES_UNLOADED   = 'EMPLOYEES_UNLOADED';
export const EMPLOYEES_ADD        = 'EMPLOYEES_ADD';
export const EMPLOYEES_DELETE     = 'EMPLOYEES_DELETE';
